create navbar html, css
GSG-CF05/Team1-Sanajib-LaunchToSpace pull request #25
Opened 2022-03-20 23:02 UTC by SundusAhmed

relate #3

2022-03-20 23:06 UTC, SaraDahman approved these changes

2022-03-20 23:11 UTC, mahmoudhammad309 submitted a review, later dismissed
well done

2022-03-20 23:14 UTC, MohammedAbuSamra submitted a review, later dismissed
شابوووو خالتو

2022-03-21 07:12 UTC, sara219 requested changes

2022-03-21 08:17 UTC, SaraDahman commented on .vscode/settings.json
> +}
I removed the file

2022-03-21 08:17 UTC, SaraDahman commented on index.html
> +              class="logo-img"
I added the logo image

2022-03-21 08:35 UTC, sara219 approved these changes

2022-03-21 08:41 UTC, MohammedAbuSamra approved these changes

2022-03-21 08:45 UTC, SaraDahman approved these changes

2022-03-21 08:47 UTC, merged